---

- hosts: "{{ dbhost }}"

  tasks:
    - name: Create a database for the new site
      mysql_db:
        name: "{{ database }}"
        state: present
      register: database_creation

    - name: Create database user for new site
      mysql_user:
        name: "{{ user }}"
        password: "{{ password }}"
        priv: "{{ database }}.*:ALL"
        state: present
      when: database_creation.changed

    - name: Create wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: "{{ wordpress_install_directory }}/wp-config.php"
        owner: wpuser
        group: wpuser
        mode: 0600




